### ISSUE TITLE
defines antes de include sem necessidade

### ISSUE THREAD

**Issue by eduardomarossi** [nicolasbss/APS2-ComputacaoEmbarcada#2]
https://github.com/nicolasbss/APS2-ComputacaoEmbarcada/blob/76df72551333ffeca0d4321fba56fb1f1dcc1483/LCD-maxTouch-Switch-Toggle/MXT_EXAMPLE_USART1/src/main.c#L141-L156

Ideal seria vir todos os defines antes dos includes (exceto quando o define altera o comportamento do include)

**Comment by nicolasbss** [comment]
edu, aqui: 

Ideal seria vir todos os defines antes dos includes (exceto quando o define altera o comportamento do include)

vc quis dizer depois do include né?
